example: fancyfy rc.init & rc.shutdown
deal with busy rootfs on shutdown

diff --git a/example/rc.init b/example/rc.init
--- a/example/rc.init
+++ b/example/rc.init
@@ -4,7 +4,7 @@
 umask 002
 export PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
 
-echo "[`ktstamp`] Starting system ..."
+echo "[`ktstamp`] Start system ..."
 
 # push environment into rund
 runc -q env PATH="$PATH"
@@ -21,8 +21,11 @@ mount -n nodev /sys -t sysfs
 mount -n nodev /proc -t proc
 
 # mount + stuff /dev
-echo "[`ktstamp`] Starting fdev ..."
-mount -n nodev /dev -t devtmpfs -o size=10M,mode=0755
+if ! grep " /dev " /proc/mounts > /dev/null; then
+	# no /dev mounted yet.
+	echo "[`ktstamp`] Mount /dev ..."
+	mount -n nodev /dev -t devtmpfs -o size=10M,mode=0755
+fi
 
 ## clean kernel configured hotplug program
 echo "" > /proc/sys/kernel/hotplug
@@ -46,14 +49,14 @@ echo "" > /proc/sys/kernel/hotplug
 } &
 
 {
-	if [ -f /etc/random-seed ]; then 
-		echo "[`ktstamp`] Setting random seed"
-		cat /etc/random-seed > /dev/urandom
+	if [ -f /var/cache/random-seed ]; then 
+		echo "[`ktstamp`] Set random seed"
+		cat /var/cache/random-seed > /dev/urandom
 	fi
 
 } &
 
-echo "[`ktstamp`] Starting filesystems ..."
+echo "[`ktstamp`] Start filesystems ..."
 # mount / read-write
 mount -n / -o remount,rw
 
@@ -66,36 +69,48 @@ mount -n / -o remount,rw
 
 {
 	while test ! -c /dev/rtc0; do sleep 0.25; done
-	echo Restoring system clock
+	echo "[`ktstamp`] Restore system clock"j
 	hwclock -su
 } &
 
-find /var/run -type f -name *.pid | xargs rm -f &
-find /var/run -type s | xargs rm -f &
+mount nodev /run -t tmpfs
+# or you could clean up /var/run
+#find /var/run -type f -name *.pid | xargs rm -f &
+#find /var/run -type s | xargs rm -f &
 
 # synchronization point
 wait
 # READY
 
-echo "[`ktstamp`] Starting syslog ..."
+# you could spawn all S* scripts in /etc/run.d parallel
+#echo "[`ktstamp`] Start /etc/run.d/ ..."
+#for FILE in /etc/run.d/S*; do
+#	$FILE start &
+#done
+#
+## wait on all scripts
+#wait
+
+# or you could place it all inline here...
+echo "[`ktstamp`] Start syslog ..."
 # syslog
 runc add syslogd -r -n
 runc add klogd -n
 
-echo "[`ktstamp`] starting logind ..."
+echo "[`ktstamp`] Start logins ..."
 # virtual terminals
 runc add TERM=linux logind /dev/tty2 /dev/tty3 /dev/tty4 /dev/tty5 /dev/tty6
 
-echo "[`ktstamp`] starting Xorg ..."
+echo "[`ktstamp`] Start Xorg session ..."
 ## Xorg
 runc add USER=kurt xinit
 
-echo "[`ktstamp`] starting SSH ..."
+echo "[`ktstamp`] Start SSH ..."
 ## ssh
 mkdir -p -m 0755 /var/run/sshd
 runc add /usr/sbin/sshd -D
 
-echo "[`ktstamp`] starting other services ..."
+echo "[`ktstamp`] Start network ..."
 #rm /var/run/ifplugd*
 ## networks
 runc add ifplugd -i lan -u1 -d0 --no-daemon --ignore-fail
